name: xqerl
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - master
jobs:
  smoke:
    name: Smoke Tests
    runs-on: ubuntu-latest
    services:
        xq:
            image: grantmacken/alpine-xqerl
            ports:
            - 8081:8081
    steps:
    - name: Flying Squirrels 
      run: |
        echo 'test'

