name: xqerl
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
        image: erlang:22.0.7
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Xqerl Dependences
      run: rebar3 get-deps
    - name: Compile Xqerl
      run: rebar3 compile
    - name: Create Xqerl Release
      run: rebar3 release -o /usr/local
    - name: Start Up Xqerl
      run: |
          ln -s /usr/local/xqerl/bin/* /usr/local/bin
          echo "$PATH"
          echo "$(which xqerl)"
          cd /usr/local/xqerl
          ls -al .
          ./bin/xqerl start
    - name: Stop Xqerl
      run: xqerl stop


    # - name: Xqerl Shell
    #   run: |
    #       rebar3 shell
    #       r3:do('application:ensure_all_started(xqerl).')



    # - name: Create Xqerl Release
    #   run: rebar3 release -o /usr/local
    # - name: Start Up Xqerl
    #   run: |
    #      ln -s /usr/local/xqerl/bin/* /usr/local/bin
    #      echo "$PATH"
    #      echo "$(which xqerl)"

  # - name: Inspect
  # spec_tests:
  #   runs-on: ubuntu-latest
  #   container:
  #       image: erlang:22.0.7
  #   steps:
  #   - name: Checkout Repo
  #     uses: actions/checkout@v1
  #     with:
  #       fetch-depth: 1
  #   - name: spec tests
  #     run: rebar3 ct --spec "test/test.specs"

