name: xqerl
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
        image: erlang:22.0.7
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Create xqerl release
      run: rebar3 release -o /usr/local
    - name: Start up xqerl
      run: |
         ln -s /usr/local/xqerl/bin /usr/local/bin
         which xqerl
         xqerl foreground
         xqerl eval 'application:ensure_all_started(xqerl).'



