name: xqerl
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
        image: erlang:22.0.7
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Compile xqerl
      run: rebar3 compile
    - name: Create xqerl release
      run: rebar3 release -o /usr/local
    - name: Start up xqerl
      run: |
         ln -s /usr/local/xqerl/bin/* /usr/local/bin
         echo "$PATH"
         echo "$(which xqerl)"
         xqerl

  # - name: Inspect
  # spec_tests:
  #   runs-on: ubuntu-latest
  #   container:
  #       image: erlang:22.0.7
  #   steps:
  #   - name: Checkout Repo
  #     uses: actions/checkout@v1
  #     with:
  #       fetch-depth: 1
  #   - name: spec tests
  #     run: rebar3 ct --spec "test/test.specs"

