name: xqerl
on: [push]
jobs:
  # spec_tests:
  #   runs-on: ubuntu-latest
  #   container:
  #       image: erlang:22.0.7
  #   steps:
  #   - name: Checkout Repo
  #     uses: actions/checkout@v1
  #     with:
  #       fetch-depth: 1
      # - name: Compile Xqerl
      # run: rebar3 compile
  #   - name: spec tests
  #     run: rebar3 ct --spec "test/test.specs"
  build:
    runs-on: ubuntu-latest
    # container:
    #     image: erlang:22.0.7
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Compile Xqerl
      run: rebar3 compile
    - name: Check Compile
      run: |
          ls _build/default
          printf %60s | tr ' ' '-' && echo
          ls _build/default/lib
          printf %60s | tr ' ' '-' && echo
          ls _build/default/lib/xqerl
          printf %60s | tr ' ' '-' && echo
          ls _build/default/lib/xqerl/ebin
          printf %60s | tr ' ' '-' && echo
          ls _build/default/lib/xqerl/include
          printf %60s | tr ' ' '-' && echo
    - name: Create Xqerl Release
      run: |
          sudo chown -R /usr/local
          rebar3 release -o /usr/local
          printf %60s | tr ' ' '-' && echo
          ln -s /usr/local/xqerl/bin/xqerl /usr/local/bin/xqerl
          printf %60s | tr ' ' '-' && echo
          which xqerl
          printf %60s | tr ' ' '-' && echo
    - name: Start Up Xqerl
      run: |
          xqerl start
          sleep 5
          xqerl ping
          xqerl pid
          xqerl stop


